//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinanzas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.leasings = new HashSet<leasing>();
        }
    
        public int idDNI { get; set; }

        [Required(ErrorMessage = "Ingrese email valido")]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Por favor ingrese un email valido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Por favor ingrese la contraseña")]
        public string password { get; set; }

        [Required(ErrorMessage = "Por favor ingrese el nombre del usuario")]
        public string NNombre { get; set; }

        [Required(ErrorMessage = "Por favor ingrese el apellido del usuario")]
        public string NApellido { get; set; }
        public int Ntipo { get; set; }

        [Required(ErrorMessage = "Por favor ingrese el RUC")]
        public string RUC { get; set; }

        [Required(ErrorMessage = "Por favor ingrese el numero telefónico")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "Por favor ingrese su direccion")]
        public string Direccion { get; set; }

        [Required(ErrorMessage = "Por favor ingrese su DNI")]
        public string DNI { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leasing> leasings { get; set; }
    }
}
